runtime: python312
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /js
  static_dir: js

- url: /ads.txt
  static_files: ads.txt
  upload: ads.txt

- url: .*
  script: auto

automatic_scaling:
  max_instances: 1

env_variables:
  PYTHONUNBUFFERED: "1"
